### ISSUE TITLE
Can you provide a voice conversion finetune recipe?

### ISSUE THREAD

**Issue by hpjang** [microsoft/SpeechT5#12]
First, Thank you, for your amazing achievements.

I tried asr finetune. It's work well!
So, I'd like to do other things too!

Such like voice conversion task!! 
Can you provide voice conversion finetune and convert recipe??

**Comment by Ajyy** [comment]
Sure! we plan to release the recipe of voice conversion task recently (about 2~3 weeks). Thanks for your attention.

**Comment by mechanicalsea** [comment]
Hi, @hpjang VC finetune and convert recipe are available after [this commit](https://github.com/microsoft/SpeechT5/commit/e9d7c0838c7605df6e61c4385f132049ffcf4ada). The [scripts](https://github.com/microsoft/SpeechT5/tree/main/SpeechT5#vc) can be helpful to implement VC fine-tuning.

We also provide re-implementation of VC fine-tuned model [speecht5_vc.pt](https://huggingface.co/mechanicalsea/speecht5-vc/blob/main/speecht5_vc.pt) and some samples, but with a smaller batch size or max updates, which can be helpful.

Thanks for you attention to our work.
