### ISSUE TITLE
Port to Huggingface 

### ISSUE THREAD

**Issue by StephennFernandes** [microsoft/SpeechT5#19]
Hey SpeechT5 Team, I've been seeing some activity of speechT5 on Huggingface. But didn't really see Huggingface version of speechT5. Could you please tell me if you guys are working on porting speechT5 to Huggingface , or perhaps it's already done. 

As i am planning to pretrain speechT5 and then further use it in Huggingface for other downstream tasks.

**Comment by wszlong** [comment]
Hi, regarding SpeechT5 models, huggingface team is helping to integrate them, please see: https://github.com/huggingface/transformers/pull/18922
