### ISSUE TITLE
Missing SPM and Vocabulary files

### ISSUE THREAD

**Issue by sumanthd17** [microsoft/SpeechT5#20]
In the README for SpeechT5, the download SPM model ([here](https://github.com/microsoft/SpeechT5/tree/main/SpeechT5#text-data)) redirects to https://github.com/microsoft/SpeechT5#language-model-and-vocabulary, but this section is missing in the README provided. Can you share the download links for the SPM model and vocabulary files.

Thanks

**Comment by Ajyy** [comment]
Sorry for the mistake, we have updated the new link to SPM model and vocabulary files, which is in [here](https://github.com/microsoft/SpeechT5/tree/main/SpeechT5#language-model-and-vocabulary). Thanks!

**Comment by sumanthd17** [comment]
Thanks for the prompt reply
