### ISSUE TITLE
Same benchmark, same architecture, but the WER is differenet, why?

### ISSUE THREAD

**Issue by splinter21** [microsoft/SpeechT5#24]
![image](https://user-images.githubusercontent.com/26759495/202732795-67e7d8f9-56e4-49a8-8e6c-09f0e8a8a011.png)
![image](https://user-images.githubusercontent.com/26759495/202732858-800823c7-56b0-499f-8177-5c3832275487.png)

Fig1 is from SpeechLM(https://arxiv.org/pdf/2209.15329.pdf), Fig2 is from SpeechUT(https://arxiv.org/pdf/2210.03730.pdf)

I notice that the WER is the same in Base Size group, but is different in Large Size group.

Why?

**Comment by zz12375** [comment]
@splinter21 Please take a close look at the experimental sections of these two papers &#x1f602;. In the first Table you posted, the WERs of Large models are fine-tuned on 960h data. While in the second Table, the WERs of Large models are fine-tuned on 100h data. You can find Table 9 in Appendix E of SpeechUT paper which matches the results of Table 1 in SpeechLM paper.

Hope the above information helps you.

**Comment by splinter21** [comment]
> @splinter21 Please take a close look at the experimental sections of these two papers 😂. In the first Table you posted, the WERs of Large models are fine-tuned on 960h data. While in the second Table, the WERs of Large models are fine-tuned on 100h data. You can find Table 9 in Appendix E of SpeechUT paper which matches the results of Table 1 in SpeechLM paper.
> 
> Hope the above information helps you.

Thanks! You dispelled my doubts.
Microsoft published lots of SSL papers in the recent months, and after comparing I find maybe SpeechUT is the best (up to now).
