### ISSUE TITLE
VATLM: ModuleNotFoundError: No module named 'fairseq.data.audio.multi_corpus_dataset_audio'

### ISSUE THREAD

**Issue by xiabingquan** [microsoft/SpeechT5#25]
Hi, there. I'm trying to extract features with the released VATLM pre-trained models. Here's what I did.

Firstly, I tried loading the pre-trained model:
```
# cwd: ..../av_hubert
import vathubert
model, cfg, task = fairseq.checkpoint_utils.load_model_ensemble_and_task(["./finetune_large_vox2_v_433h.pt"])
```
but an error occurs: `AssertionError: Could not infer task type from {'_name': 'vat_hubert_pretraining'...`. 
It's because the task `vat_hubert_pretraining` wasn't been successfully registered by `Fairseq`, and the reason for this error is that the sub-package `vathubert.tasks` is not successfully initialized since there's not `__init__.py` in it (from what I know, if there're not `__init__.py`, it's just a "NameSpace" package instead of a normal package). To fix it, I add `__init__.py` to `./vathubert/tasks.py`, which content is 
```
from .vathubert_pretraining import VATHubertPretrainingTask
```
This is for registering the task in Fairseq. However, another error occurs in 
https://github.com/microsoft/SpeechT5/blob/996bb4219ce1890a9984eff9dda65855af4cb446/VATLM/vat_hubert/vathubert/tasks/vathubert_pretraining.py#L40
> ModuleNotFoundError: No module named 'fairseq.data.audio.multi_corpus_dataset_audio'

I read the source code of Fairseq and didn't find the file `multi_corpus_dataset_audio.py` in the directory [`fairseq.data.audio`](https://github.com/facebookresearch/fairseq/tree/afc77bdf4bb51453ce76f1572ef2ee6ddcda8eeb/fairseq/data/audio)

Did I miss anything? Or is there some bug in the code? Any help is appreciated, Thanks!

**Comment by zqs01** [comment]
@xiabingquan Thanks for the question, I forgot to put `multi_corpus_dataset_audio.py` in the folder. You put `multi_corpus_dataset_audio.py` in the `fairseq/data/audio/` folder and this problem will be solved.
```
# Copyright (c) Facebook, Inc. and its affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

import logging
from os import replace
import time
from collections import OrderedDict
from typing import Any, Dict, List, Optional

import numpy as np
from fairseq.data import data_utils

from fairseq.data import FairseqDataset

logger = logging.getLogger(__name__)


class MultiCorpusDataset(FairseqDataset):
    """
    Stores multiple instances of FairseqDataset together.
    Unless batch_sample=True, requires each instance
    to be the same dataset, as the collate method needs to work on batches with
    samples from each dataset.

    Allows specifying a distribution over the datasets to use. Note that unlike
    MultiCorpusSampledDataset, this distribution allows sampling for each item,
    rather than on a batch level. Note that datasets with sampling probabilty
    of 0 will be skipped.

    Each time ordered_indices() is called, a new sample is generated with
    the specified distribution.

    Args:
        datasets: a OrderedDict of FairseqDataset instances.
        distribution: a List containing the probability of getting an utterance from
                        corresponding dataset
        seed: random seed for sampling the datsets
        sort_indices: if true, will sort the ordered indices by size
        batch_sample: if true, will ensure each batch is from a single dataset
    """

    def __init__(
        self,
        datasets: Dict[str, FairseqDataset],
        max_positions: Dict,
        distribution: List[float],
        max_tokens_ratio: List[float],
        seed: int,
        sort_indices: bool = False,
        distributed_rank: Optional[int] = None,
    ):
        super().__init__()
        assert isinstance(datasets, OrderedDict)
        assert len(datasets) == len(distribution)
        # assert sum(distribution) == 1
        self.datasets = datasets
        self.distribution = distribution
        self.max_tokens_ratio = max_tokens_ratio
        self.seed = seed
        self.sort_indices = sort_indices
        self.distributed_rank = distributed_rank
        self.max_positions = max_positions

        # Avoid repeated conversions to list later
        self.dataset_list = list(datasets.values())
        self.total_num_instances = 0

        # first_dataset = self.dataset_list[0]

        self.num_instances_per_dataset = []
        self.dataset_offsets = []
        for i, dataset in enumerate(self.dataset_list):
            assert isinstance(dataset, FairseqDataset)
            # assert type(dataset) is type(first_dataset)
            self.num_instances_per_dataset.append(
                0 if self.distribution[i] == 0 else len(dataset)
            )
            self.dataset_offsets.append(self.total_num_instances)
            self.total_num_instances += self.num_instances_per_dataset[i]

    def ordered_indices(self):
        start = time.time()
        with data_utils.numpy_seed(self.seed, self.epoch):
            logger.info(f"sampling new dataset with seed {self.seed} epoch {self.epoch}")
            sampled_indices = {}

            # For each dataset i, sample self.distribution[i] * self.total_num_instances
            for i, key in enumerate(self.datasets):
                tp = time.time()
                if self.distribution[i] == 0:
                    # skip dataset if sampling probability is 0
                    continue

                if i < len(self.datasets) - 1:
                    num_instances = int(self.distribution[i] * self.total_num_instances)
                    high = self.dataset_offsets[i + 1]
                else:
                    num_instances = int(self.distribution[i] * self.total_num_instances)
                    high = self.total_num_instances

                logger.info(f"sampling {num_instances} from {key} dataset")

                # First, add k copies of the dataset where k = num_instances // len(dataset).
                # This ensures an equal distribution of the data points as much as possible.
                # For the remaining entries randomly sample them
                dataset_size = len(self.datasets[key])
                num_copies = num_instances // dataset_size
                dataset_indices = np.random.permutation(high - self.dataset_offsets[i])[: num_instances - num_copies * dataset_size]
                if num_copies > 0:
                    dataset_indices = np.concatenate(
                            (
                                np.repeat(
                                    np.arange(high - self.dataset_offsets[i]), num_copies
                                ),
                                dataset_indices,
                            )
                        )
                # ### filter by size
                # if self.max_positions[key] is not None:
                #     dataset_indices, ignored = self.datasets[key].filter_indices_by_size(
                #         dataset_indices,
                #         self.max_positions[key],
                #     )
                #     if len(ignored) > 0:
                #         logger.warning(
                #             (
                #                 "{:,} samples have invalid sizes and will be skipped, "
                #                 "max_positions={}, first few sample ids={}"
                #             ).format(len(ignored), self.max_positions[key], ignored[:10])
                #         )
            
                if self.sort_indices:
                    logger.info(" - sampled indices took {}s".format(time.time() - tp))
                    tp = time.time()
                    dataset_indices = np.sort(dataset_indices)
                    dataset_indices = self.datasets[key].ordered_indices()[dataset_indices] + self.dataset_offsets[i]
                    logger.info(" - ordered_indices took {}s".format(time.time() - tp))
                else:
                    np.random.shuffle(dataset_indices)
                
                sampled_indices[key] = dataset_indices

            logger.info(
                "multi_corpus_dataset ordered_indices took {}s".format(
                    time.time() - start
                )
            )
            return sampled_indices

    def _map_index(self, index: int):
        """
        If dataset A has length N and dataset B has length M
        then index 1 maps to index 1 of dataset A, and index N + 1
        maps to index 1 of B.
        """
        counter = 0
        for num_instances, key in zip(self.num_instances_per_dataset, self.datasets):
            if index < counter + num_instances:
                return index - counter, key
            counter += num_instances
        raise ValueError(
            "Invalid index: {}, max: {}".format(index, self.total_num_instances)
        )

    def __len__(self):
        """
        Length of this dataset is the sum of individual datasets
        """
        return self.total_num_instances

    def __getitem__(self, index):
        new_index, key = self._map_index(index)
        try:
            item = self.datasets[key][new_index]
            item["full_id"] = index
            return item
        except Exception as e:
            e.args = (f"Error from {key} dataset", *e.args)
            raise

    def collater(self, samples):
        """
        If we are doing batch sampling, then pick the right collater to use.

        Otherwise we assume all collaters are the same.
        """
        if len(samples) == 0:
            return None
        
        samples_dict = {key: [] for key in self.datasets}
        for s in samples:
            _, key = self._map_index(s["full_id"])
            samples_dict[key].append(s)
        
        batch = {}
        for key in samples_dict:
            if len(samples_dict[key]) == 0:
                continue
            batch[key] = self.datasets[key].collater(samples_dict[key])

        return batch


    def num_tokens(self, index: int):
        index, key = self._map_index(index)
        return self.datasets[key].num_tokens(index)

    def size(self, index: int):
        index, key = self._map_index(index)
        return self.datasets[key].size(index)

    @property
    def can_reuse_epoch_itr_across_epochs(self):
        return False

    def set_epoch(self, epoch, **unused):
        super().set_epoch(epoch)
        logger.info(f"setting epoch of multi_corpus_dataset to {epoch}")
        for ds in self.dataset_list:
            if hasattr(ds, "set_epoch"):
                ds.set_epoch(epoch)
        self.epoch = epoch

    @property
    def supports_prefetch(self):
        return False

    @property
    def supports_fetch_outside_dataloader(self):
        return all(
            self.datasets[key].supports_fetch_outside_dataloader
            for key in self.datasets
        )
        

    def batch_by_size(
        self,
        indices,
        max_tokens=None,
        max_sentences=None,
        required_batch_size_multiple=1,
    ):    
        dataset_indices = indices
        batches_dict = {}
        for n, key in enumerate(dataset_indices):
            max_tokens_ratio = self.max_tokens_ratio[n]
            cur_batches = super().batch_by_size(
                np.array(dataset_indices[key], dtype=np.int64),
                round(max_tokens * max_tokens_ratio),
                max_sentences,
                required_batch_size_multiple,
            )
            logger.info(f"Created {len(cur_batches)} batches for dataset {key}")
            batches_dict[key] = cur_batches

        return batches_dict


    def get_batch_sampler(
        self,
        indices,
        num_shards,
        seed,
        max_tokens=None,
        max_sentences=None,
        required_batch_size_multiple=1,
        split_modality_batch=False,
    ):

        def batch_sampler(dataset, epoch):
            start = time.time()
            batches_dict = dataset.batch_by_size(
                indices,
                max_tokens=max_tokens,
                max_sentences=max_sentences,
                required_batch_size_multiple=required_batch_size_multiple,
            )
            logger.info(f"multi_corpus_dataset, batch_by_size took {time.time() - start}s")
            start = time.time()
            new_batches = []

            ### shuffle inner group size, split into speech/text batches
            shuffled_batches_list = []
            speech_batches = []
            ### we should specify the speech_batches because: we need concatenate different speech datasets (e.g. ltr or km) instead of loading them parellelly.
            for name, batches in batches_dict.items():
                batches = inner_bucket_shuffle(batches, seed+epoch, num_shards*10)
                batches = batches[: (len(batches) // num_shards) * num_shards]
                if len(batches) == 0:
                    logger.warning(f"Sample 0 batch for {name}, you should ensure that no {name} data provided.")
                elif name.startswith("speech"):
                    speech_batches += batches
                else:
                    batches = shuffle_buckets(batches, seed=seed+epoch, inner_shuf=False)
                    shuffled_batches_list.append(batches)
            # speech_batches = shuffle_buckets(speech_batches, seed=seed+epoch, inner_shuf=False)
            # shuffled_batches_list.append(speech_batches)

            ### create the final new_batches
            num_batch = min(len(batches) for batches in shuffled_batches_list)
            if split_modality_batch:
                for i in range(0, num_batch, num_shards):
                    for batches in shuffled_batches_list:
                        new_batches += batches[i: i + num_shards]
            else:
                for i in range(num_batch):
                    new_batches.append(np.concatenate([batches[i] for batches in shuffled_batches_list]))

            logger.info(f"multi_corpus_dataset sample {len(new_batches)} batches, took {time.time() - start}s")
            return new_batches
        
        def inner_bucket_shuffle(batches, seed, bucket_size=10, thr=0):
            """we assert batches is sorted form long to short.
                shuffle samples in a buctet(e.g. 10 batches).
                batches: a list of numpy array"""
            num_batch = len(batches)
            new_batches = []
            num_buckets = len(batches) // bucket_size
            i = 0
            while i < num_batch:
                if (i < bucket_size * thr or 
                    i >= bucket_size * (num_buckets - thr)
                ):
                    new_batches.append(batches[i])
                    i += 1
                else:
                    group = np.concatenate(batches[i: i+bucket_size])
                    with data_utils.numpy_seed(seed):
                        np.random.shuffle(group)
                    new_batches += np.array_split(group, bucket_size)
                    i += bucket_size
            assert all([len(batch) > 0 for batch in new_batches])
            return new_batches
        
        def shuffle_buckets(batches, seed, inner_shuf=True):
            if inner_shuf:
                batches = inner_bucket_shuffle(batches, seed, num_shards*10)
            batches = [batches[i: i + num_shards] for i in range(0, len(batches)-num_shards+1, num_shards)]
            assert len(batches[-1]) == num_shards
            new_batches = []
            with data_utils.numpy_seed(seed):
                np.random.shuffle(batches)
                for group in batches:
                    new_batches += group
            return new_batches
        
        return batch_sampler

```

**Comment by xiabingquan** [comment]
@zqs01 Thanks for your quick reply. It did solve the problem. However, I come across another problem. When I'm trying to load the pre-trained model [VatLM-Large	VoxCeleb2 + LRS3 + paired audio+text+audio-no finetune](https://drive.google.com/file/d/1_vbVFpKcaaPcCx2FtI-GyzVvxAhppg_b/view?usp=share_link) using the following codes, an error occurred
```
ckpt_ph = "./VoxCeleb2_LRS3_paired-audio-text-audio_pretrain.pt"
model, cfg, task = fairseq.checkpoint_utils.load_model_ensemble_and_task(
            [ckpt_ph]
        )
```

The full tracebrack is as follows:
> Traceback (most recent call last):
  File "<input>", line 2, in <module>
  File "/home/xiabingquan/repos/fairseq/fairseq/checkpoint_utils.py", line 473, in load_model_ensemble_and_task
    model = task.build_model(cfg.model, from_checkpoint=True)
  File "/home/xiabingquan/repos/fairseq/fairseq/tasks/fairseq_task.py", line 340, in build_model
    model = models.build_model(cfg, self, from_checkpoint)
  File "/home/xiabingquan/repos/fairseq/fairseq/models/__init__.py", line 106, in build_model
    return model.build_model(cfg, task)
  File "/home/xiabingquan/repos/SpeechT5/VATLM/vathubert/models/vathubert.py", line 456, in build_model
    model = VATHubertModel(cfg, task.cfg, task.dictionaries, **kwargs)
  File "/home/xiabingquan/repos/SpeechT5/VATLM/vathubert/models/vathubert.py", line 407, in __init__
    self.encoder = TransformerEncoder(cfg)
  File "/home/xiabingquan/repos/fairseq/fairseq/models/wav2vec/wav2vec2.py", line 953, in __init__
    self.required_seq_len_multiple = args.required_seq_len_multiple
  File "/home/xiabingquan/miniconda3/envs/lrs/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 305, in __getattr__
    self._format_and_raise(key=key, value=None, cause=e)
  File "/home/xiabingquan/miniconda3/envs/lrs/lib/python3.8/site-packages/omegaconf/base.py", line 95, in _format_and_raise
    format_and_raise(
  File "/home/xiabingquan/miniconda3/envs/lrs/lib/python3.8/site-packages/omegaconf/_utils.py", line 629, in format_and_raise
    _raise(ex, cause)
  File "/home/xiabingquan/miniconda3/envs/lrs/lib/python3.8/site-packages/omegaconf/_utils.py", line 610, in _raise
    raise ex  # set end OC_CAUSE=1 for full backtrace
  File "/home/xiabingquan/miniconda3/envs/lrs/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 303, in __getattr__
    return self._get_impl(key=key, default_value=DEFAULT_VALUE_MARKER)
  File "/home/xiabingquan/miniconda3/envs/lrs/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 361, in _get_impl
    node = self._get_node(key=key)
  File "/home/xiabingquan/miniconda3/envs/lrs/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 383, in _get_node
    self._validate_get(key)
  File "/home/xiabingquan/miniconda3/envs/lrs/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 135, in _validate_get
    self._format_and_raise(
  File "/home/xiabingquan/miniconda3/envs/lrs/lib/python3.8/site-packages/omegaconf/base.py", line 95, in _format_and_raise
    format_and_raise(
  File "/home/xiabingquan/miniconda3/envs/lrs/lib/python3.8/site-packages/omegaconf/_utils.py", line 694, in format_and_raise
    _raise(ex, cause)
  File "/home/xiabingquan/miniconda3/envs/lrs/lib/python3.8/site-packages/omegaconf/_utils.py", line 610, in _raise
    raise ex  # set end OC_CAUSE=1 for full backtrace
omegaconf.errors.ConfigAttributeError: Key 'required_seq_len_multiple' not in 'VATHubertConfig'
	full_key: required_seq_len_multiple
	reference_type=Optional[VATHubertConfig]
	object_type=VATHubertConfig

After reading the source code, I found that this error is caused by the incorrect configuration files used in `vathubert/models/vathubert.py` when initializing the `TransformerEncoder`.
https://github.com/microsoft/SpeechT5/blob/a7b72c6932e82930eb01331c2c922a0687157367/VATLM/vat_hubert/vathubert/models/vathubert.py#L402

The `TransformerEncoder` is imported from Wav2Vec2, so the input cfg should be a [`Wav2Vec2Config`](https://github.com/facebookresearch/fairseq/blob/main/fairseq/models/wav2vec/wav2vec2.py) instead of a [VATHubertConfig](https://github.com/microsoft/SpeechT5/blob/main/VATLM/vat_hubert/vathubert/models/vathubert.py)
https://github.com/microsoft/SpeechT5/blob/a7b72c6932e82930eb01331c2c922a0687157367/VATLM/vat_hubert/vathubert/models/vathubert.py#L24-L27

Since the above two dataclasses have a lot of different keys, Fairseq will throw errors when accessing a key that exists in `Wav2Vec2Config` but not int `VATHubertConfig`, such as the above `required_seq_len_multiple`. This error could be fixed by manually adding the keys of `Wav2Vec2Config` to `VATHubertConfig`, but this strategy isn't elegant and may lead to some potential errors (For example, Wav2Vec2 may quantize and mask the inputs, which is definitely what we want when extracting features). How can we fix this problem? Or am I doing something wrong? 
One thing is note is that is I encountered the same problem when I was trying to load the pre-trained models of AVHuBERT(since both of you use the same template), but it seems that other people is working fine with the original codes. Bothered a lot.

**Comment by zqs01** [comment]
@xiabingquan Since the AV-HuBERT and VATLM codes are not placed in the fairseq default folder, you need to specify the loading path. The following code can load AV-HuBERT and VATLM. I hope these can help you.
```
from argparse import Namespace
import fairseq
from fairseq import checkpoint_utils, utils 

utils.import_user_module(Namespace(user_dir='/path/to/vat_hubert/vathubert'))
models, saved_cfg, task = checkpoint_utils.load_model_ensemble_and_task(["/path/to/model"])

print(saved_cfg)

```

**Comment by xiabingquan** [comment]
> @xiabingquan Since the AV-HuBERT and VATLM codes are not placed in the fairseq default folder, you need to specify the loading path. The following code can load AV-HuBERT and VATLM. I hope these can help you.
> 
> ```
> from argparse import Namespace
> import fairseq
> from fairseq import checkpoint_utils, utils 
> 
> utils.import_user_module(Namespace(user_dir='/path/to/vat_hubert/vathubert'))
> models, saved_cfg, task = checkpoint_utils.load_model_ensemble_and_task(["/path/to/model"])
> 
> print(saved_cfg)
> ```

Thanks for the hint, but it's not my problem here. My problem is that, inside the `__init__` method of `VATHubertModel`, 
https://github.com/microsoft/SpeechT5/blob/a7b72c6932e82930eb01331c2c922a0687157367/VATLM/vat_hubert/vathubert/models/vathubert.py#L24-L27
https://github.com/microsoft/SpeechT5/blob/a7b72c6932e82930eb01331c2c922a0687157367/VATLM/vat_hubert/vathubert/models/vathubert.py#L402
when initializing the `TransformerEncoder`, it passes a `VATHubertConfig` instead of a `Wav2Vec2Config`, which leads to further errors
> File "/home/xiabingquan/miniconda3/envs/lrs/lib/python3.8/site-packages/omegaconf/_utils.py", line 610, in _raise
raise ex # set end OC_CAUSE=1 for full backtrace
omegaconf.errors.ConfigAttributeError: Key 'required_seq_len_multiple' not in 'VATHubertConfig'
full_key: required_seq_len_multiple
reference_type=Optional[VATHubertConfig]
object_type=VATHubertConfig

For example, as the above trackback shows, the program tries to access the attribute `required_seq_len_multiple ` of the input `args`  by calling `self.required_seq_len_multiple = args.required_seq_len_multiple`, but `required_seq_len_multiple` is an valid key only for `Wav2Vec2Config` while not for `VATHubertConfig`. [AVHubert](https://github.com/facebookresearch/av_hubert/blob/5ab235b3d9dac548055670d534b283b5b70212cc/avhubert/hubert.py#L399) has exactly the same issue.

I solved my problem by adding the keys needed to initialize `TransformerEncoder` to `VATHubertConfig` with the following two steps.
Step1.
Add  `LAYER_TYPE_CHOICES = ChoiceEnum(["transformer", "conformer"])` after https://github.com/microsoft/SpeechT5/blob/a7b72c6932e82930eb01331c2c922a0687157367/VATLM/vat_hubert/vathubert/models/vathubert.py#L61-L62

Step2: Add the following lines
```
    layer_type: LAYER_TYPE_CHOICES = field(
        default="transformer", metadata={"help": "layer type in encoder"}
    )   # No masking
    pos_conv_depth: int = field(
        default=1,
        metadata={"help": "depth of positional encoder network"},
    )
    max_positions: int = field(default=100000, metadata={"help": "Max positions"})
    checkpoint_activations: bool = field(
        default=False,
        metadata={"help": "recompute activations and save memory for extra compute"},
    )
    # FP16 optimization
    required_seq_len_multiple: int = field(
        default=1,
        metadata={
            "help": "pad the input to encoder such that the sequence length is divisible by multiple"
        },
    )
    # Conformer
    depthwise_conv_kernel_size: int = field(
        default=31,
        metadata={
            "help": "depthwise-conv-kernel-size for convolution in conformer layer"
        },
    )
    attn_type: str = field(
        default="",
        metadata={"help": "if espnet use ESPNET MHA"},
    )
    pos_enc_type: str = field(
        default="abs",
        metadata={"help": "Positional encoding type to use in conformer"},
    )
    fp16: bool = field(default=False, metadata={"help": "If fp16 is being used"})
```
after https://github.com/microsoft/SpeechT5/blob/a7b72c6932e82930eb01331c2c922a0687157367/VATLM/vat_hubert/vathubert/models/vathubert.py#L318

This way, the missing keys are added to `VATHubertConfig` and `TransformerEncoder` could be initialized happily.

I'm not sure whether I've done it the right way, but it does work. The question is, some keys missing shouldn't happen since it's a very big bug and could be easily spotted, so I guess it's mostly my problem instead of the repo's. Any reply on how to load models without any modification to the original codes is welcomed. Thanks! : )

**Comment by xiabingquan** [comment]
btw, thanks for the great work!!!

**Comment by zqs01** [comment]
@xiabingquan I haven't tried this method for loading models before, thank you for your solution. If you have new questions, you can reopen issues or contact me by email.
