### ISSUE TITLE
SpeechT5: Finetuned SID model

### ISSUE THREAD

**Issue by entn-at** [microsoft/SpeechT5#31]
Would it be possible to share the SpeechT5 model finetuned on VoxCeleb1 for the SID task? (I noticed the re-implemented [VC](https://huggingface.co/mechanicalsea/speecht5-vc/) and [TTS](https://huggingface.co/mechanicalsea/speecht5-tts/) models shared on HF).

**Comment by mechanicalsea** [comment]
Hi, @entn-at 

Thanks for you attention to our SID model. We are going to release the SpeechT5 model fine-tuned on the SID task in several weeks. Also, the dataset manifest and scripts will be re-implemented and uploaded on huggingface.

**Comment by entn-at** [comment]
Many thanks @mechanicalsea!
