### ISSUE TITLE
Missing speecht5 task 

### ISSUE THREAD

**Issue by maximerenou** [microsoft/SpeechT5#37]
Hello,

The following Inference instructions seem outdated :
https://github.com/microsoft/SpeechT5/tree/main/SpeechT5#inference-1

The script `SpeechT5/scripts/generate_speech.py` trigger this error when using `--task speecht5` :
```
generate_speech.py: error: argument --task: invalid choice: 'speecht5' (choose from 'hubert_pretraining', 'denoising', 'multilingual_denoising', 'translation', 'multilingual_translation', 'translation_from_pretrained_bart', 'translation_lev', 'language_modeling', 'speech_to_text', 'legacy_masked_lm', 'online_backtranslation', 'simul_speech_to_text', 'simul_text_to_text', 'audio_pretraining', 'semisupervised_translation', 'sentence_prediction', 'cross_lingual_lm', 'translation_from_pretrained_xlm', 'masked_lm', 'sentence_ranking', 'translation_multi_simple_epoch', 'multilingual_masked_lm', 'dummy_lm', 'dummy_masked_lm', 'dummy_mt')
```

Thanks

**Comment by mechanicalsea** [comment]
Hi, @maximerenou 

It seems that the task of "speecht5" is not included in fairseq.tasks. It can be solved by adding `${USER_DIR}` to `--user-dir`, where `${USER_DIR}` is the path to speecht5 code.

Wish it helpful.
