### ISSUE TITLE
Pretrain SpeechT5 on my own dataset

### ISSUE THREAD

**Issue by hungker** [microsoft/SpeechT5#38]
If i want to pretrain SpeechT5 on my own dataset, how can i get the xvector ?

**Comment by mechanicalsea** [comment]
The released pre-trained model is used to extract the xvector as [this way](https://github.com/microsoft/SpeechT5/issues/16#issuecomment-1279890887) in #16.

**Comment by hungker** [comment]
Thank you very much. By the way, how to use the SPM model? I didn't see the tutorial

**Comment by Ajyy** [comment]
You can refer to [sentencepiece](https://github.com/google/sentencepiece) git repo for more details about SPM model.
