### ISSUE TITLE
Missing text_to_speech_dataset.py in speecht5/data

### ISSUE THREAD

**Issue by ayushtues** [microsoft/SpeechT5#4]
In `from speecht5.data.text_to_speech_dataset` used [here](https://github.com/microsoft/SpeechT5/blob/f0d75b9f8119c044d05b195bd974c414d4f47265/SpeechT5/speecht5/tasks/speecht5.py#L27), it seems like a `text_to_speech_dataset.py` file is missing in the speecht5/data folder, like other similar files present in it

**Comment by Ajyy** [comment]
Hi,

Currently, we do not update the code for the text-to-speech task. So I delete the related code and it should be OK now.
