### ISSUE TITLE
No code for Speech Synthesis

### ISSUE THREAD

**Issue by petervickers** [microsoft/SpeechT5#8]
Code for finetuning speech synthesis with the predicted log Mel-filterbank features, as described in the SpeechT5 paper, is not availiable.

Is it possible to provide this?

Many thanks

**Comment by Ajyy** [comment]
Hi, @mechanicalsea is preparing the code of TTS. Please stay tuned for further updates! Thanks!

**Comment by mechanicalsea** [comment]
> Hi, @mechanicalsea is preparing the code of TTS. Please stay tuned for further updates! Thanks!

Got it. I will prepare the code of TTS and release it as soon as possible.

**Comment by mechanicalsea** [comment]
> Code for finetuning speech synthesis with the predicted log Mel-filterbank features, as described in the SpeechT5 paper, is not availiable.
> 
> Is it possible to provide this?
> 
> Many thanks

Hello, the TTS code and scripts are prepared after [this](https://github.com/microsoft/SpeechT5/commit/9ee63bfbda0ed44345c1ebdd52bf88b77dfceab5) commit.

The [scripts](https://github.com/microsoft/SpeechT5/tree/main/SpeechT5#tts) and [manifest](https://huggingface.co/mechanicalsea/speecht5-tts) can be helpful to implement SpeechT5 TTS. And we also did implement it, and it can generate frequent speech utterances.

Thanks for you attention to our work.

**Comment by mechanicalsea** [comment]
Hi, @petervickers We provide additional re-implementation of TTS fine-tuned model [speecht5_tts.pt](https://huggingface.co/mechanicalsea/speecht5-tts/blob/main/speecht5_tts.pt) and generated samples, but with a smaller batch size or max updates, which can be helpful.
