### ISSUE TITLE
Speech conversion: process whole input without stopping

### ISSUE THREAD

**Issue by holmbuar** [microsoft/SpeechT5#92]
I have followed the example in the [Huggingface blog post](https://huggingface.co/blog/speecht5), and can replicate that voice conversion example in a Colab session. The voice conversion stops consistently in the middle of the example input sentence. 

Noob question: where do I start making the model convert all the audio in the input? Is this a software engineering problem (cut audio with some silence detection logic, loop through sending audio-only to converter), or is it more of a fine-tuning or parameter adjusting effort?

The end goal would be to use the SpeechT5 model to replicate the product ElevenLabs is offering. There you can upload a sound file up to 50 MB, and expect a voice conversion that time-wise matches the whole input. 

Appreciate any hint or tips @XiaoshanHsj

**Comment by XiaoshanHsj** [comment]
sorry, i am not the author of SpeechT5.
